### PR TITLE
Pull Request to Merge WMS ID 11635 more Lab 9 updates

### PR DESCRIPTION
**Pull request by billburton67**
WMS ID 11635

Pull Request to Merge WMS ID 11635 more Lab 9 updates

@hope-fisher

### CODE REVIEW

**Review by hope-fisher — COMMENTED** [review]
Hi @billburton67, this PR is showing zero files changed. You may need to Commit to Main from your GitHub desktop for them to show here.

**Comment by hope-fisher** [comment]
Looks like there was a recent big PR ([#577](https://github.com/oracle-livelabs/database/pull/577)) that was approved and merged. If this PR is redundant, no worries. If you do have additional changes, please tag me when you have them committed so that I can review the file changes.

**Comment by billburton67** [comment]
Thanks @hope-fisher .. Half awake this morning .  Seems that a commit to my main that was done after the PR #577 was requested made it in when PR #577 was actually merged.  Closing PR

**Comment by hope-fisher** [comment]
Even better! Sounds good.

**Pull request closed without merging**
