### PR TITLE
LWMS ID 11389: Inithial creation from development folder. Made change…

### PR DESCRIPTION
**Pull request by plforacle**
…s recommended by Adrienne Howard

LWMS ID 11389: Inithial creation from development folder. Made changes recommended by Adrienne Howard
1.	 Before VCN -do we need to create a compartment?  Generally root should not be used -correct? -done
2.	Lab 1 Task 4  - text says compartment rood -image shows compartment heatwave
3.	Is the PAR URL correct? ???
4.	Create took about 30 minutes   ??
5.	Lab 2 Task 3 -says to keep the shape -but then we change it?  Also the screens shots are out of date so it is a bit confusing. - done
6.	Lab 3, Task 3 Step 4 there is a type-should be 3 not 31  -done
I could not enable the MySql HeatWave Lakehouse Option. -  done
8.	Adding the cluster takes about 30 minutes
9.	Had to disable point in time backups to enable lakehouse
10.	 This is the correct statement for Lab 4 Task 2 step 3 SELECT table_name, table_rows FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'mysql_customer_orders';
Lab 6  – screen shots of the query results would help – if we have time
Delivery-vendor.pq is in the wrong folder -causes ALTER TABLE to fail.
Lab 7 – some screen shots of results would be nice if we have time -but all instructions work.
At the beginning of each lab -it would be nice to re-include the instructions on how to connect to the compute node and then the MySQL Db.  If you get disconnected – it is hard to find the instructions on how to do this

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by plforacle** [comment]
I have received approval from the Product team's Abhinav Agarwal to publish this workshop.

**Comment by hope-fisher** [comment]
Hi @plforacle , please update the image alternate text to more accurately match the image. This is the text within ![ ]

**Comment by plforacle** [comment]
Hi Hope,
I don’t understand this request.

Thank you,
Perside Lafrance Foster | MySQL Principal Partners Solution Engineer
email: ***@***.******@***.***>
phone: 1.786.877.9063
Oracle  Florida

From: Hope Fisher ***@***.***>
Sent: Thursday, June 29, 2023 5:18 PM
To: oracle-livelabs/database ***@***.***>
Cc: Perside Foster ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/database] LWMS ID 11389: Inithial creation from development folder. Made change… (PR #293)


Hi @plforacle<https://urldefense.com/v3/__https:/github.com/plforacle__;!!ACWV5N9M2RV99hQ!Lxmxwj2SRfmZT4hmkm3HpmFYFqHHofxLpfkIIv3weyUh8JIAIej1wme_93GHw1AHmIVZ7Jn_a3qbdHiGySaeJYUlk_TJ$> , please update the image alternate text to more accurately match the image. This is the text within ![ ]

**Comment by plforacle** [comment]
LWMS ID 11389: Made changes requested by Hope Fisher
Pease update the image alternate text to more accurately match the image. This is the text within ![ ]

**Review by hope-fisher — APPROVED** [review]

**Pull request merged**
