### PR TITLE
(#11767) New workshop from DBA Essentials - install database 23ai

### PR DESCRIPTION
**Pull request by manish-garodia**
Hello,

We have developed a new workshop - Install Oracle Database 23ai on OCI Compute, WMS ID is #11767.

Oracle Database 23ai (23.6) GA was Oct 15, Tue. Therefore, to compliment the database release, we would like to publish our workshops from the DBA Essentials series for 23ai. Would be great if you approve this PR please so that we could proceed with publishing to production on priority. Remaining workshops from the series would follow suit and we intend to publish them all in the next 2 weeks.

Thanks a lot for your help and support.

~MG

### CODE REVIEW

**Comment by klazarz** [comment]
@manish-garodia please resolve the branch out-of-date issue

**Review by carmenberdant1 — CHANGES_REQUESTED** [review]
Hi @manish-garodia, you need to replace all the old links from the index.html files. Additionally, in the intro-install.md file first note is empty.

**Comment by manish-garodia** [comment]
Have updated the inde.html file with the latest. The note looks ok as we are using building-blocks in the workshop.

**Review by carmenberdant1 — APPROVED** [review]

**Comment by manish-garodia** [comment]
thank you!

**Pull request merged**
