### PR TITLE
(7041, 8321, 8341) Move workshops location

### PR DESCRIPTION
**Pull request by manish-garodia**
Hi,

As discussed with Michelle, created a folder `dba-essentials` under version-specific folder `odb-21c`, which indicates Oracle Database 21c.
Moved the workshops under `odb-21c/dba-essentials`:
- configure-network-env
- install-db
- remove-db

`No change` to lab contents.

Please approve the PR. Thank you
~MG

### CODE REVIEW

**Review by arabellayao — APPROVED** [review]
Hi Manish! Please make sure to update those workshops' URLs in the publishing tab in WMS.

**Comment by manish-garodia** [comment]
Hi Arabella, thanks for approving the PR. 
I do not think I understand the new objectstorage URLs very well. Could you please suggest what to do. 
Thanks

**Comment by arabellayao** [comment]
Hi Manish! You can create object storage URL for your workshop by combining the object storage prefix of the database repo (https://objectstorage.us-phoenix-1.oraclecloud.com/p/KNnfJD8PskLUcpiy55OJ4GjaMSFvEJD6TKEzBi6E88AXNfBKKgl7HbLVTU2oxdO1/n/c4u02/b/database/o/) and the path to your workshop's index.html file.

**Comment by manish-garodia** [comment]
Okay. The workshop is at this location in the database repo: 
database/odb-21c/dba-essentials/install-db 

So, the URL would be: 

https://objectstorage.us-phoenix-1.oraclecloud.com/p/KNnfJD8PskLUcpiy55OJ4GjaMSFvEJD6TKEzBi6E88AXNfBKKgl7HbLVTU2oxdO1/n/c4u02/b/database/o/database/odb-21c/dba-essentials/install-db/workshops/freetier/index.html 

If this is correct, I will go ahead and update WMS for this workshop and for others too.

**Comment by arabellayao** [comment]
Hi Manish! The link should be:
https://objectstorage.us-phoenix-1.oraclecloud.com/p/KNnfJD8PskLUcpiy55OJ4GjaMSFvEJD6TKEzBi6E88AXNfBKKgl7HbLVTU2oxdO1/n/c4u02/b/database/o/**odb-21c/dba-essentials/install-db/workshops/freetier/index.html**. You only need to append your workshop path **within the repo**. I suggest you wait after the sync between GitHub repo and object storage tonight, verify all the links can render workshops correctly, and then update them in WMS.

**Comment by manish-garodia** [comment]
Sure. Thanks, Arabella! :thumbsup:

**Pull request merged**
