### PR TITLE
Ajay Joshi WMS 11453 OraGitPush1:main Data Sovereignty Lab uds23c folder initial upload

### PR DESCRIPTION
**Pull request by OraGitPush1**
WMS 11453

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by OraGitPush1** [comment]
Ajay Joshi WMS 11453 OraGitPush1:main Data Sovereignty Lab uds23c folder initial upload #366

**Review by rahul-tasker — CHANGES_REQUESTED** [review]
Please use meaningul names for your images. Some are left as "Screen Shot..." 

Refer to the self QA document to ensure the rest of your lab is compliant: https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx

**Comment by OraGitPush1** [comment]
Updates for QA check

**Review by anooshapilli — COMMENTED** [review]
@OraGitPush1 - Could you add the WMS ID of the other folder being updated - initialize-environment in this PR?

**Comment by OraGitPush1** [comment]
WMS ID 11453 for all updates in this pull request

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
