### PR TITLE
WMS 705 & WMS 1: Updated manifest for OCW

### PR DESCRIPTION
**Pull request by klazarz**
WMS 705: Updated manifest for OCW

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi Kevin! multitenant-new folder does not seem to belong to WMS #705. Can you add that workshop's WMS ID as well? Thanks!

**Comment by klazarz** [comment]
@arabellayao good catch. thanks. i have fixed it now

**Review by arabellayao — APPROVED** [review]

**Comment by arabellayao** [comment]
Hi Kevin! Seems like your branch is some commits behind the oracle-livelabs main branch. Can you update your branch? Thanks!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi Kevin! Seems like your branch is some commits behind the oracle-livelabs main branch. Can you update your branch? Thanks!

**Comment by klazarz** [comment]
done

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
