### PR TITLE
Review and image update complete

### PR DESCRIPTION
**Pull request by hope-fisher**
# WMS ID 11382

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ZRTalke — CHANGES_REQUESTED** [review]
@hope-fisher 
Hi Hope,

Please provide the WMS ID. Additionally I noticed there are files containing uppercase letters such as JSON-doc-created.png and SQL-constraint-1.png. Could you please update all those as well? All filenames must only contain lowercase letters.

Thank you!

**Comment by ZRTalke** [comment]
Additionally the file names need to be descriptive like adb-provision instead of l4-s3 etc

**Comment by hope-fisher** [comment]
Thanks for the feedback. Changes made to filenames. WMS ID confirmed.

**Comment by ZRTalke** [comment]
Hi Hope! Did you update your pull request? I'm seeing the WMS ID but still seeing files with uppercase letters on my end...

**Pull request closed without merging**
