### PR TITLE
WMS ID#11283 - Updating our "Oracle XML DB: Storing and Processing XML Documents" workshop

### PR DESCRIPTION
**Pull request by hroyofc**
XML DB tutorials for LiveLabs.

WMS ID#11283 : Oracle XML DB: Storing and Processing XML Documents

Updating our XML DB workshop for LiveLabs. This is the initial commit.

### CODE REVIEW

**Comment by anooshapilli** [comment]
@hroyofc - Looks like this is a new workshop. Please submit the filled-out [Self QA document](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) once the workshop development is finished to  [livelabs-help-db_us@oracle.com](mailto:livelabs-help-db_us@oracle.com)  mailbox for review and update the workshop status to Self QA Complete in WMS. If everything looks good we will approve the PR.

**Comment by hroyofc** [comment]
Thank you! Completed the QA form and sent it to livelabs-help-db_us@oracle.com.

**Review by kamryn-v — COMMENTED** [review]
Hi @hroyofc, 
1. the estimated time in the introduction, populate.md, queries.md, relational2xml.md, update.md, and xml2relational.md says XYZ. This will need to be replaced with the estimated time.
2. The images in populate.md, queries.md, relational2xml.md, update.md, and xml2relational.md do not have the alt text. The alt text should explain what the image looks like for handicap accessibility. If an image cannot be described in short text alternative, it must not be used.

**Comment by hroyofc** [comment]
@kamryn-v Thanks for reviewing.
Both of them are addressed. Please take a look.

**Comment by anooshapilli** [comment]
@hroyofc - There are quite a few changes needed to be made to the workshop. I will update the workshop status to Self QA. Please review the Self QA checklist in WMS for your workshop and make the necessary changes to update the workshop. Once you have thoroughly performed the Self QA of the workshop, update the status to Self QA Complete. 

As this is PR is more than a week ago. I will be closing the PR for now. Please create a new PR after making the necessary changes to the workshop.

**Comment by hroyofc** [comment]
@anooshapilli I am not sure what changes you are talking about. Can you please tell me what are these?

**Pull request closed without merging**
