### PR TITLE
11054: Changed name of workshop to include 'search'.

### PR DESCRIPTION
**Pull request by RogerFord**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by william-masdon-oracle — CHANGES_REQUESTED** [review]
We do not allow binary files (like your files.zip or pangrams.pdf) in our repo. If you would like to have the user download a file, please email it to livelabs-help-db_us@oracle.com and they will provide you an Object Storage PAR link to include in your workshop.

**Comment by anooshapilli** [comment]
@RogerFord - Following up on this PR. Please move the binary files to object storage.

**Comment by kamryn-v** [comment]
Hi @RogerFord, Can you please remove the files from GitHub and update the PARs in the PR?
Thanks!

**Comment by anooshapilli** [comment]
@RogerFord - In the binary.md file, number the steps in task 1 and number the tasks correctly(task 2 is repeated twice).

**Comment by anooshapilli** [comment]
As this PR is open for about two weeks, closing this PR. Please make these changes (update binary.md file and remove the files folder) and create a new PR.

**Pull request closed without merging**
