### PR TITLE
WMS ID#11028 

### PR DESCRIPTION
**Pull request by ramdonti**

### CODE REVIEW

**Comment by anooshapilli** [comment]
@ramdonti - For the need-help lab, you can use object storage links to the need-help labs in your manifest.json instead of copying the lab files. Use the below links:

For LiveLabs version: https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-livelabs.md

For the free tier version: https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-freetier

Similarly, update the get started lab links in manifest.json with the object storage link 
free tier - https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/cloud-login/pre-register-free-tier-account.md 

livelabs - https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/cloud-login/cloud-login.md

**Comment by anooshapilli** [comment]
As this is a new workshop, please submit the filled out  [Self QA document](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) to  [livelabs-help-db_us@oracle.com](mailto:livelabs-help-db_us@oracle.com)  mailbox for review. If everything looks good we will approve the PR and move the workshop to production.

**Comment by ramdonti** [comment]
> @ramdonti - For the need-help lab, you can use object storage links to the need-help labs in your manifest.json instead of copying the lab files. Use the below links:
> 
> For LiveLabs version: https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-livelabs.md
> 
> For the free tier version: https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-freetier
> 
> Similarly, update the get started lab links in manifest.json with the object storage link free tier - https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/cloud-login/pre-register-free-tier-account.md
> 
> livelabs - https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/cloud-login/cloud-login.md

updated the changes

**Comment by ramdonti** [comment]
> As this is a new workshop, please submit the filled out [Self QA document](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) to [livelabs-help-db_us@oracle.com](mailto:livelabs-help-db_us@oracle.com) mailbox for review. If everything looks good we will approve the PR and move the workshop to production.

QA checklist document shared to [livelabs-help-db_us@oracle.com](mailto:livelabs-help-db_us@oracle.com)

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
