### PR TITLE
LWMS ID: 11520 - Initial creation of Livelab "Heatwave Lakehouse: Rea…

### PR DESCRIPTION
**Pull request by plforacle**
…ltime Asset Maintenance"

Added All created and tested labs
Lab 1: Create Demo Compartment and ObjectStore Buckets and upload Data Lab 2a: Create VCN and Compartment for workshop
Lab 2b: Create Compute instance for workshop and configure MySQL Shell Lab 2c: Create MySQL Database System in Oracle Cloud Lab 2d: Enable Lakehouse and Create MFG_SENSOR Database/Table in MySQL Database System Lab 3: Build ML model API to evalaute the probablity of device faiures Lab 4a: Set up OCI Stream service & Execute Sensor Data Simulator Lab 4b: Setup Dynamic Group for function to manage stream/objects Lab 5: Set up and Deploy OCI function and connect to service connector Hub Lab 6(a): Set up OCI Dataflow and deploy a Pyspark Application and load the datasets Lab 6(b): Load the datasets from demo-events-silver-mysqlhw to MYSQL HW Lab 7: Design and Develop OAC Dashboards
Lab 8: Set up OCI Data Catalog

# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ramonamagadan18 — COMMENTED** [review]
Hi @plforacle! Can you please send me the development link for this workshop? Thank you!

**Comment by plforacle** [comment]
https://github.com/plforacle/database
https://github.com/plforacle/database/tree/main/heatwave-lakehouse-cdp
https://plforacle.github.io/database/heatwave-lakehouse-cdp/workshops/livelabs/index.html


Perside Lafrance Foster | MySQL Principal Partners Solution Engineer
email: ***@***.******@***.***>
phone: 1.786.877.9063
Oracle  Florida

From: Ramona Magadan ***@***.***>
Sent: Thursday, November 28, 2024 3:14 AM
To: oracle-livelabs/database ***@***.***>
Cc: Perside Foster ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/database] LWMS ID: 11520 - Initial creation of Livelab "Heatwave Lakehouse: Rea… (PR #728)


@ramonamagadan18 commented on this pull request.

Hi @plforacle<https://urldefense.com/v3/__https:/github.com/plforacle__;!!ACWV5N9M2RV99hQ!PrPfhpOyj8yWkstP_5uvMqk9FvU9IEUojg_1UqNaUdnx_IOaBEMidqLk6NoZCireHUytku51WTkgv8OMaHCtGNNeQOmX$>! Can you please send me the development link for this workshop? Thank you!

**Comment by plforacle** [comment]
Team, 
Please try to deploy this pull request as soon as possible and move this LiveLab to production. The HeatWave PM team needs to have this published for their next step session. I will be away from my computer from Dec 4th to Dec 16th and will not be able to make any more changes until then. So, please help me finish this task by the end of day Friday. I live in Florida and will be available to connect at 7 am ET. Thank you in advance.

**Comment by plforacle** [comment]
Team, 
Bhushan and I have made all of the requested changes. Please approve and deploy to production as soon as you can. Thank you.

**Review by ramonamagadan18 — APPROVED** [review]

**Pull request merged**
