### PR TITLE
WMS 11070 - Free tier documentation

### PR DESCRIPTION
**Pull request by aberinnj**
# 11070

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x] All filenames are lower case (including folders, images, files, etc.)
- [x] Filenames are descriptive
- [x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues of your PR:
1. Use this index.html (copy the content) for all your index.html: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/index.html 
2. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json index.html, instead of learning-library links. Refer to this file for example: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/manifest.json
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

**Comment by aberinnj** [comment]
@arabellayao done! Please let me know if this is good. I
- renamed files and their references with underscores instead of hyphens per the QA form instructions
- updated how to display Note per the QA form instructions
- Added Proceed texts
- Updated first words of each title to imperative form

**Comment by madhusudhanrao-ppm** [comment]
Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json index.html, instead of learning-library links. Refer to this file for example: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy/manifest.json
Please refer to the [self QA form](https://objectstorage.us-ashburn-1.oraclecloud.com/p/MKKRgodQ0WIIgL_R3QCgCRWCg30g22bXgxCdMk3YeKClB1238ZJXdau_Jsri0nzP/n/c4u04/b/qa-form/o/QA.docx) for details and let me know if you have any questions. Thanks!

image

**Comment by aberinnj** [comment]
I see I missed the Get Started link under `manifest.json` and made the recent commit! Thank you for the help

**Comment by arabellayao** [comment]
Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.

**Pull request closed without merging**
