### PR TITLE
WMS ID 11044

### PR DESCRIPTION
**Pull request by devinderpalsingh**

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! For the need-help labs, you do not need to copy any lab files. You can use object storage links to the need-help labs in your manifest.json: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-livelabs.md" for LiveLabs version, "https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-freetier" for free tier version.

**Comment by devinderpalsingh** [comment]
> Hi! For the need-help labs, you do not need to copy any lab files. You can use object storage links to the need-help labs in your manifest.json: "https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-livelabs.md" for LiveLabs version, "https://objectstorage.us-phoenix-1.oraclecloud.com/p/SJgQwcGUvQ4LqtQ9xGsxRcgoSN19Wip9vSdk-D_lBzi7bhDP6eG1zMBl0I21Qvaz/n/c4u02/b/common/o/labs/need-help/need-help-freetier" for free tier version.

Done the changes and pushed to main. Please do let me know for any concerns.

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please also update the links in manifest.json for "Get Started" labs. For index.html files, you can copy the index.html from "https://github.com/oracle-livelabs/em-omc/blob/main/enterprise-manager/odb-21c/dba-essentials/em-dba/workshops/freetier/index.html."

**Comment by devinderpalsingh** [comment]
> Hi! Please also update the links in manifest.json for "Get Started" labs. For index.html files, you can copy the index.html from "https://github.com/oracle-livelabs/em-omc/blob/main/enterprise-manager/odb-21c/dba-essentials/em-dba/workshops/freetier/index.html."

Done, Please check and let me know for any concerns.

**Review by arabellayao — APPROVED** [review]

**Pull request merged**
