### PR TITLE
LWMS ID 11507: Added missing index file

### PR DESCRIPTION
**Pull request by aiijazfatima**
# Add here your WMS ID

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Comment by aiijazfatima** [comment]
Please deploy this as soon as possible. Users are not able to access this site.

**Review by carmenberdant1 — CHANGES_REQUESTED** [review]
Hi @aiijazfatima the bitly link in this index.html file is outdated. Please use the index.html from the common file. I'll dm you the path.

**Comment by carmenberdant1** [comment]
@aiijazfatima this branch is out-of-date please merge it with the latest changes

**Review by anacoman11 — CHANGES_REQUESTED** [review]
Hi @aiijazfatima, please add the right WMS ID in the title of the PR, resolve the branch out-of-date issue and replace the https://bit.ly/golivelabs URL with https://livelabs.oracle.com

**Review by klazarz — CHANGES_REQUESTED** [review]
@aiijazfatima please change href in Oracle LiveLabs anchor to livelabs.oracle.com

  <a href="https://livelabs.oracle.com" target="_blank" id="livelabs" title="Oracle LiveLabs"></a>

**Pull request closed without merging**
