### PR TITLE
LWMS ID 11114: Deploy to production

### PR DESCRIPTION
**Pull request by plforacle**
[LWMS ID 11114: Made all image names lower case ...Deploy to production ... includes Arabella requested changes ,,, Made @arabellayao requested changes

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues with your workshop:
1. Make sure images' names are all lower cases (including "IP), and use dashes instead of underscores.
2. zip file should be uploaded to GitHub. Please email the zip file and have our team upload to object storage.
3. You have the "heatwave-machine-learning" folder under a "heatwave-machine-learning" folder, and have repetitive files. Please correct the folder structure
Thank you!

**Comment by plforacle** [comment]
Please copy the attached zip file to object storage and send me the link.

I am currently retrieving the file from  https://plforacle.github.io/learning-library/data-management-library/mysql-se/heatwave-machine-learning/develop/files/iris.zip

Thank you,
Perside Foster | MySQL Principal Partners Solution Engineer
email: ***@***.******@***.***>
phone: 1.786.877.9063
Oracle  Florida

From: Arabella Yao ***@***.***>
Sent: Friday, July 15, 2022 5:36 PM
To: oracle-livelabs/database ***@***.***>
Cc: Perside Foster ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-livelabs/database] LWMS ID 11114: Deploy to production (PR #32)


@arabellayao requested changes on this pull request.

Hi! Please fix the following issues with your workshop:

  1.  Make sure images' names are all lower cases (including "IP), and use dashes instead of underscores.
  2.  zip file should be uploaded to GitHub. Please email the zip file and have our team upload to object storage.
  3.  You have the "heatwave-machine-learning" folder under a "heatwave-machine-learning" folder, and have repetitive files. Please correct the folder structure
Thank you!

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! Please fix the following issues for your PR:
1. Make sure all images’ filenames are lower case
2. Use the [oracle-livelabs.github.io](http://oracle-livelabs.github.io/) links in manifest.json and index.html, instead of learning-library links. Refer to these files for examples: https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop/workshops/tenancy
Thanks!

**Comment by madhusudhanrao-ppm** [comment]
Please make all image names lower case

image

**Review by madhusudhanrao-ppm — APPROVED** [review]

**Pull request merged**
