### PR TITLE
WMS ID 11145 OCI DMS - Online migration

### PR DESCRIPTION
**Pull request by jorgeame**
# Add here your WMS ID
WMS ID 11145
# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x ] All filenames are lower case (including folders, images, files, etc.)
- [x ] Filenames are descriptive
- [x ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [x ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [x ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@jorgeame - Please make the image file name lowercase to approve the PR
image

**Comment by jorgeame** [comment]
yes, it used to be capital but as this screen of the change shows I changed to lower:

image

**Comment by jorgeame** [comment]
The local file name was also changed before my pull request:

image

**Comment by jorgeame** [comment]
Hello Anoosha, yes, it used to be capital but as this screen of the change shows I changed to lower:

[image]
[image]

Thanks
Jorge

From: Anoosha Pilli ***@***.***>
Sent: Monday, August 14, 2023 6:20 PM
To: oracle-livelabs/database ***@***.***>
Cc: Jorge Martinez ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-livelabs/database] WMS ID 11145 OCI DMS - Online migration (PR #370)


@anooshapilli commented on this pull request.

@jorgeame<https://urldefense.com/v3/__https:/github.com/jorgeame__;!!ACWV5N9M2RV99hQ!OcmoC2erPYLRxa3dj_uUhxvWOs8SVMdZIUGQWVwj_xCB2RCkeF0wq9tlnWfJdeOxbiRD5dviUM0wgMnIGTu2-RZ_qDoGFg$> - Please make the image file name lowercase to approve the PR
[image]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/63126232/260599125-0e73315c-7f9e-4a13-bfba-901eaf50dfa3.png__;!!ACWV5N9M2RV99hQ!OcmoC2erPYLRxa3dj_uUhxvWOs8SVMdZIUGQWVwj_xCB2RCkeF0wq9tlnWfJdeOxbiRD5dviUM0wgMnIGTu2-RbsUc9E1w$>

**Review by rahul-tasker — CHANGES_REQUESTED** [review]
See previous comments

**Review by rahul-tasker — APPROVED** [review]

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
