### PR TITLE
WMS ID #11455 - Learn how to use RAFT Replication to build resilient distributed databases

### PR DESCRIPTION
**Pull request by deekshasehgal**
# Add here your WMS ID #11455 - Raft Replication workshop

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by ZRTalke — CHANGES_REQUESTED** [review]
Hi @deekshasehgal 

While reviewing your pull request I noticed a couple areas that need to be updated:

- In file and image names please replace all _ with - and make sure all characters are lowercase as per naming guidelines
- The help email in your manifest.json files needs to be livelabs-help-db_us@oracle.com to match your WMS stakeholder
- Per self QA guidelines, labs should not reference Always Free or Free Tier. Please remove these references from the intro and other md files

Let me know if you have any questions. Thanks!

**Comment by deekshasehgal** [comment]
Hello Team,

I have made the requested changes and please find below the response inline:


•	In file and image names please replace all _ with - and make sure all characters are lowercase as per naming guidelines ----> Done
•	The help email in your manifest.json files needs to be [livelabs-help-db_us@oracle.com](mailto:livelabs-help-db_us@oracle.com) to match your WMS stakeholder ---->Done
•	Per self QA guidelines, labs should not reference Always Free or Free Tier. Please remove these references from the intro and other md files -----> Removed from intro.md file but the md file for the "Get Started" section is coming from the common labs "https://oracle-livelabs.github.io/common/labs/cloud-login/cloud-login.md". We did not change any file from common labs.

Thanks. 
Please let me know the next steps.

**Comment by ZRTalke** [comment]
Hi @deekshasehgal 

For the removing the free tier references from the other md files I'm referring to removing references such as in the prerequisites section of prepare-setup and initialize-environment such as below
This lab assumes you have:
- An Oracle Free Tier or Paid Cloud account

The other changes look good. Thanks!

**Review by ZRTalke — APPROVED** [review]

**Comment by deekshasehgal** [comment]
Hello @ZRTalke 

I have made the requested changes in rest of the files too, before you approved the request. You must have seen the updates.
Removed "Free-tier and Paid Tenants"  from the files prepare-setup.md, initialize-environment.md and topology.md .

Thanks.

**Pull request merged**
