### PR TITLE
 OCI DMS - Online migration  WMS ID 11145

### PR DESCRIPTION
**Pull request by jorgeame**
I have included a ocw-livelabs folder since we are working on a cloudworld green button, this was advised by the livelabs team helping us.

### CODE REVIEW

**Review by arabellayao — CHANGES_REQUESTED** [review]
Hi! As shown in WMS, workshop 11145 is located under database/dms-online. It seems like you are updating files outside of this folder. Please add the WMS IDs of all workshops that have been updated. Thanks!

**Comment by jorgeame** [comment]
> Hi! As shown in WMS, workshop 11145 is located under database/dms-online. It seems like you are updating files outside of this folder. Please add the WMS IDs of all workshops that have been updated. Thanks!

Hello Arabella,

In OCI DMS - Online migration WMS ID 11145 #68 I meant to add the following folder:
database/dms-online/workshops/livelabs/ which is inside  database/dms-online.

Please confirm if I am doing somethig wrong.

**Comment by arabellayao** [comment]
Hi! The dms-online folder is good, but you are also changing the edition-based-redefinition folder, which does not seem to belong to the workshop. Also make sure you get the latest updates from oracle-livelabs.
Screen Shot 2022-08-26 at 11 04 19 AM
Screen Shot 2022-08-26 at 11 04 09 AM

**Comment by jorgeame** [comment]
> Hi! The dms-online folder is good, but you are also changing the edition-based-redefinition folder, which does not seem to belong to the workshop. Also make sure you get the latest updates from oracle-livelabs. Screen Shot 2022-08-26 at 11 04 19 AM
> 
> Screen Shot 2022-08-26 at 11 04 09 AM

Thanks Arabella, let me close this one and start a clean one.

**Pull request closed without merging**
