### PR TITLE
Ops Insights for MySQL HeatWave DB System

### PR DESCRIPTION
**Pull request by SindhujaReddy-VT**
Ops Insights for MySQL HeatWave DB System

### CODE REVIEW

**Comment by carmenberdant1** [comment]
Hi @SindhujaReddy-VT, please resolve the branch out-of-date issue

**Review by anacoman11 — CHANGES_REQUESTED** [review]
Hi @SindhujaReddy-VT, please add the WMS ID in the title of PR and resolve the branch out-of-date issue

**Comment by SindhujaReddy-VT** [comment]
@carmenberdant1 @anacoman11 LWMS ID:2860  - Added Lab 4 Enable and explore Ops Insights for HeatWave MySQL and also updated the branch.

**Review by anacoman11 — COMMENTED** [review]
Hi @SindhujaReddy-VT, please resolve the branch out-of-date issue

**Comment by SindhujaReddy-VT** [comment]
> Hi @SindhujaReddy-VT, please resolve the branch out-of-date issue

Done!

**Review by anacoman11 — COMMENTED** [review]
Hi @SindhujaReddy-VT, please resolve the branch out-of-date issue

**Comment by SindhujaReddy-VT** [comment]
> Hi @SindhujaReddy-VT, please resolve the branch out-of-date issue and blur the compartment from:
> 
> * opsi-demo-mode-on.png
> * employeesdb-database.png
> * database-storage.png
> * database-cpu2.png
> * database-capacity-planning.png
> * database-capacity-planning-mysql.png

Hi @anacoman11 and @carmenberdant1,
I updated the Last Updated By/Date field from the Acknowledgements section for all updated files (i.e.,introduction.md file)

Regarding the screenshots mentioned, I am not using any of our compartments for the simulation. It is in Demo Mode, enabled to showcase the simulations, and will remain the same for all users. For this reason, I did not blur the compartment name. I hope this clarifies!

Thank you!

**Review by anacoman11 — APPROVED** [review]

**Pull request merged**
