### PR TITLE
WMS ID: 11371 - Content for a new LiveLab

### PR DESCRIPTION
**Pull request by SylajaK**
# WMS ID: 11371

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

### CODE REVIEW

**Review by anooshapilli — COMMENTED** [review]
@SylajaK - Please update the old console screenshots to the latest UI.

**Comment by anooshapilli** [comment]
@SylajaK - Just following up on this PR.

**Comment by SylajaK** [comment]
> @SylajaK - Just following up on this PR.

@anooshapilli, I had updated two screenshots in [Task 1: Choose ATP-S from the Services Menu](https://brijd.github.io/database/microtx-xa-stock-broker-app/workshops/tenancy/index.html?qa=true&lab=adb-provision#Task1:ChooseATPSfromtheServicesMenu).

Can you please let me know which screenshots are you referring to when you say update the old console screenshots to the latest UI? I have taken the screenshots by logging in to OCI console. Is there a repo where standard screenshots are readily available for reuse?
•	[Lab 2: Set Up the Environment](https://brijd.github.io/database/microtx-xa-stock-broker-app/workshops/tenancy/index.html?lab=setup-compute-novnc-ssh) – the screenshots in this lab are from the common repo 
•	Lab 4: Provision Autonomous Databases for use as Resource Manager – screenshots are from the OCI console. I have updated the screenshots for ATP-Serverless too.
•	[Lab 5: Trade Stocks with the Bank and Stock-Trading Application](https://brijd.github.io/database/microtx-xa-stock-broker-app/workshops/tenancy/index.html?lab=run-xa-app) – Screenshots in this lab are of the sample application that the customer builds and runs. These are not screenshots of an OCI service.
•	[Lab 6: Clean Up the Environment](https://brijd.github.io/database/microtx-xa-stock-broker-app/workshops/tenancy/index.html?lab=cleanup-stack) – is a lab from the common repo

**Comment by anooshapilli** [comment]
@SylajaK - As discussed in our call today, please update the Lab 4 screenshots.

**Comment by SylajaK** [comment]
> @anooshapilli, I have updated the screenshots based on our discussion. Kindly review the changes and provide your approval.

**Review by anooshapilli — APPROVED** [review]

**Pull request merged**
