### PR TITLE
WMS ID: 11283

### PR DESCRIPTION
**Pull request by NetoDios**
# Comments on the changes
Update XMLDB course, more consistant naming, and pointing to examples
## Notes
In Lab 1 (Task 2.3, and video), we name the database TEXTDB
In Lab 2 (Task 1.6) the database is referred as XMLDB
In Lab 3 (Task 3.6) the database is referred as XMLDB
In Lab 4 (Task 1.6) the database is referred as XMLDB
In Lab 5 (Task 2.6) the database is referred as XMLDB
In Lab 6 (Task 1.6) the database is referred as XMLDB
In Lab 7 (Task 3.6) the database is referred as XMLDB

In Lab 3 and Lab 7, it would be really helpful to have examples on each section, maybe not for everything but some can help to fully understand the languages described, that said it’s nice that a reference to an extensive description is added (for Query and SQL/XML)
I like the fact that these are self contained and that someone can refer to a specific Lab and know everything they need, but it seems a bit redundant to have Task 1, Task 2 and Task 3 the exact same in both Labs (Lab 3 and Lab 7). Perhaps this is because Tasks 1 and 2 are not steps in the process, they’re explanation of the language instead.
The introduction to both Labs is very similar and almost the same, but with minor changes, these changes aren’t regarding the main porpoise of the Lab. Although the Objectives in both Labs are spot on.
To not make heavy changes I suggest maintaining most as it is, but add a little comment to see an example on the same Lab.

As an aditional comment, I’ll add that some of the walk-through videos are too fast to keep on, the first one I saw I was trying to keep up with, until I realized I should be doing the Tasks first and refer the the video for extra visual support. In my case it would’ve been really helpful if the videos were slower.

Besides this the course is good, and introduces most things you can use.

### CODE REVIEW

**Comment by anooshapilli** [comment]
@NetoDios - Please add the WMS ID of the workshop being updated in the PR title.

**Comment by NetoDios** [comment]
Where can I find my WMS ID?

**Comment by anooshapilli** [comment]
@NetoDios - Let me Slack/email you. I couldn't find the details, could you share your Slack/email id to contact you.

**Comment by NetoDios** [comment]
Ernesto Alvarez (ernalvar)

**Review by kamryn-v — APPROVED** [review]

**Pull request merged**
